version: 3.1.{build}
image: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
services:
- mssql2017
- postgresql101
- mysql
before_build:
- cmd: >-

    nuget restore

    choco install codecov
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-

    dotnet test "%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\EntityFramework.Exceptions.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception" -c Release

    codecov -f "%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml"